name: George Jones
favicon: null
layout_spectrum: 0.37104441970586777
typography_spectrum: 0.9117981994058937
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6566632662434131
  lightness: 0.8664849172346294
  saturation: 0.6408272329717875
  rhythmicContrast: 0.28364045289345086
purpose: []
