name: George Jones
favicon: null
layout_spectrum: 0.5560531625524163
typography_spectrum: 0.9117981994058937
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.5559050287120044
  lightness: 0.9027605140581727
  saturation: 0.8388758380897343
  rhythmicContrast: 0.023755321046337485
purpose: []
